name: Build Dispatcher

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make build file
        run: |
          npm install
          npm run build
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: webwizard99/salt-store-backend.git
          event-type: build_dispatch
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "message": "build dispatch activated"}'
