name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: npm install
    - name: create build file
      run: npm run build
    - uses: actions/checkout@v2
      with:
        repository: webwizard99/salt-store-backend.git
        repo-token: 4e01d9eb906aa380869262d1556f6ed8a5099fd7
        path: backend
    - name: enumerate file structure
      run: 
        ls
    - name: delete existing build folder in backend repo
      run:
        rm -r backend/public/build
    - name: move build folder to backend repo
      run:
        mv build backend/public
    - name: add changes to backend repo
      run:
        git add .
    - name: configure git email
      run:
        git config --global user.email "michael_bragg99@hotmail.com"
    - name: configure git user name
      run:
        git config --global user.name "webwizard99"
    - name: commit changes to backend repo
      run:
        git commit -m "Update build folder"
    - name: push changes to backend repo
      run:
        git push origin master
